   services:
     db:
       image: mysql:8.0
       container_name: sanitatrix_mysql
       restart: always
       environment:
         MYSQL_ROOT_PASSWORD: root123
         MYSQL_DATABASE: sanitatrix_db
         MYSQL_USER: sanitatrix
         MYSQL_PASSWORD: sanitatrix123
       ports:
         - "3307:3306"
       volumes:
         - db_data:/var/lib/mysql

   volumes:
     db_data: